# ========= Communication Setup ========
DEVICENAME = '/dev/cu.usbserial-FT9BTHA3'
BAUDRATE = 115200

# ========= Feedback Switch & Index =========
FEEDBACK_POSITION_ENABLE = True 
FEEDBACK_POSITION_NAME = 'pos'

FEEDBACK_VELOCITY_ENABLE = True
FEEDBACK_VELOCITY_NAME = 'vel'

FEEDBACK_PWM_ENABLE = False
FEEDBACK_PWM_NAME = 'pwm'

FEEDBACK_TEMPERATURE_ENABLE = True
FEEDBACK_TEMPERATURE_NAME = 'tmp'

FEEDBACK_CURRENT_ENABLE = True
FEEDBACK_CURRENT_NAME = 'cur'

FEEDBACK_VOLTAGE_ENABLE = False
FEEDBACK_VOLTAGE_NAME = 'vol'



