# ========== Communication Setup ==========
DXL_ID = 1
PROTOCOL_VERSION = 2.0
BAUDRATE = 115200
DEVICENAME = '/dev/cu.usbserial-FT9BTHA3' 

# ========== Operating Modes ==========
ADDR_OPERATING_MODE = 11
MODE_VELOCITY = 1
MODE_POSITION = 3
MODE_EXTENDED_POSITION = 4
MODE_PWM = 16

# ========== Torque Control ==========
ADDR_TORQUE_ENABLE = 64
TORQUE_DISABLE = 0
TORQUE_ENABLE = 1

# ========== Position Control ==========
ADDR_GOAL_POSITION = 116
ADDR_PRESENT_POSITION = 132
ADDR_PROFILE_VELOCITY = 112
ADDR_PROFILE_ACCELERATION = 108
ADDR_POSITION_P_GAIN = 84
ADDR_POSITION_I_GAIN = 82
ADDR_POSITION_D_GAIN = 80

DEFAULT_P_GAIN = 800
DEFAULT_I_GAIN = 0
DEFAULT_D_GAIN = 0

POSITION_MIN = 0
POSITION_MAX = 4095  # 12-bit resolution ≈ 0–360°

# ========== Velocity Control ==========
ADDR_GOAL_VELOCITY = 104
ADDR_PRESENT_VELOCITY = 128
ADDR_VELOCITY_LIMIT = 44

VELOCITY_MIN = -1023
VELOCITY_MAX = 1023

# ========== PWM Control ==========
ADDR_GOAL_PWM = 100
ADDR_PRESENT_PWM = 124
ADDR_PWM_LIMIT = 36

# ========== Feedback ==========
ADDR_PRESENT_CURRENT = 126
ADDR_PRESENT_POSITION = 132
ADDR_PRESENT_VELOCITY = 128
ADDR_PRESENT_INPUT_VOLTAGE = 144
ADDR_PRESENT_TEMPERATURE = 146

# ========== Status Return ==========
ADDR_STATUS_RETURN_LEVEL = 68
STATUS_RETURN_ALL = 2
STATUS_RETURN_READ = 1
STATUS_RETURN_NONE = 0

# ========== Hardware Info ==========
ADDR_MODEL_NUMBER = 0
ADDR_FIRMWARE_VERSION = 6

# ========== EEPROM Lock ==========
ADDR_LOCK = 120
LOCK_OFF = 0
LOCK_ON = 1