LIDAR_DEVICENAME = "/dev/ttyUSB1"
LIDAR_BAUDRATE = 460800

IMU_ACCELERATION_ENABLE = True
IMU_ACCELERATION_NAME = "acc"

IMU_GYROSCOPE_ENABLE = True
IMU_GYROSCOPE_NAME = "gyr"

IMU_MEGNETIC_ENABLE = True
IMU_MEGNETIC_NAME = "meg"
