LIDAR_DEVICENAME = "/dev/ttyUSB1"
# LIDAR_DEVICENAME = "/dev/ttyUSB0"
# LIDAR_DEVICENAME = "/dev/cu.usbserial-210" 
LIDAR_BAUDRATE = 460800
LIDAR_ANGLEAR_RESOLUTION = 0.72 # degree
LIDAR_SAMPLE_PER_CIRCLE = int(360 / LIDAR_ANGLEAR_RESOLUTION)

LIDAR_QUALITY_ENABLE = True
LIDAR_QUALITY_NAME = "qua"

LIDAR_DISTANCE_ENABLE = True
LIDAR_DISTANCE_NAME = "dis"

LIDAR_START_FLAG_ENABLE = True
LIDAR_START_FLAG_NAME = "stf"

IMU_ACCELERATION_ENABLE = True
IMU_ACCELERATION_NAME = "acc"

IMU_GYROSCOPE_ENABLE = True
IMU_GYROSCOPE_NAME = "gyr"

IMU_MEGNETIC_ENABLE = True
IMU_MEGNETIC_NAME = "meg"
